### PR TITLE
Bump New CM fonts to version 6.0.0

### PR DESCRIPTION
**Pull request by mkorje**

### CODE REVIEW

**Comment by laurmaedje** [comment]
I'm trying to validate that the font files are correct (I have no worries at all, but better safe than sorry), but CTAN is down ^^

**Comment by laurmaedje** [comment]
And even though there are various CTAN mirrors, their search feature seems to use ctan.org.

**Comment by mkorje** [comment]
Maybe you can download from miktex? https://miktex.org/Package/Details/newcomputermodern It seems to be up, but I can't find where to download the actual package.

**Comment by mkorje** [comment]
Or there is the repo itself, https://git.gnu.org.ua/newcm.git/.

**Comment by laurmaedje** [comment]
I'll just wait until tomorrow and see then. I'm also waiting on the next Libertinus Serif release anyway.

**Comment by laurmaedje** [comment]
CTAN is back.

**Pull request merged**
